//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIBaitap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chitietdonhang
    {
        public int mact { get; set; }
        public Nullable<int> madonhang { get; set; }
        public Nullable<int> Id { get; set; }
        public string tensp { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<int> thanhtien { get; set; }
    }
}
