//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIBaitap.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CuaHangEntities4 : DbContext
    {
        public CuaHangEntities4()
            : base("name=CuaHangEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Chitietdonhang> Chitietdonhangs { get; set; }
        public virtual DbSet<donhang> donhangs { get; set; }
        public virtual DbSet<LoaiSanPham> LoaiSanPhams { get; set; }
        public virtual DbSet<LoaiTaiKhoan> LoaiTaiKhoans { get; set; }
        public virtual DbSet<sanpham> sanphams { get; set; }
        public virtual DbSet<thanhvien> thanhviens { get; set; }
    
        public virtual ObjectResult<get_allhoadon_Result> get_allhoadon()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_allhoadon_Result>("get_allhoadon");
        }
    
        public virtual int get_dangky(string tentv, string tendangnhap, string matkhau, string diachi, string sdt, Nullable<int> maloaitk)
        {
            var tentvParameter = tentv != null ?
                new ObjectParameter("tentv", tentv) :
                new ObjectParameter("tentv", typeof(string));
    
            var tendangnhapParameter = tendangnhap != null ?
                new ObjectParameter("tendangnhap", tendangnhap) :
                new ObjectParameter("tendangnhap", typeof(string));
    
            var matkhauParameter = matkhau != null ?
                new ObjectParameter("matkhau", matkhau) :
                new ObjectParameter("matkhau", typeof(string));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("diachi", diachi) :
                new ObjectParameter("diachi", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var maloaitkParameter = maloaitk.HasValue ?
                new ObjectParameter("maloaitk", maloaitk) :
                new ObjectParameter("maloaitk", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("get_dangky", tentvParameter, tendangnhapParameter, matkhauParameter, diachiParameter, sdtParameter, maloaitkParameter);
        }
    
        public virtual ObjectResult<get_hanghet_Result> get_hanghet()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_hanghet_Result>("get_hanghet");
        }
    
        public virtual ObjectResult<get_hoadonAdmin_Result> get_hoadonAdmin(Nullable<int> trangthai)
        {
            var trangthaiParameter = trangthai.HasValue ?
                new ObjectParameter("trangthai", trangthai) :
                new ObjectParameter("trangthai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_hoadonAdmin_Result>("get_hoadonAdmin", trangthaiParameter);
        }
    
        public virtual ObjectResult<get_hoadonUser_Result> get_hoadonUser(Nullable<int> trangthai, Nullable<int> id)
        {
            var trangthaiParameter = trangthai.HasValue ?
                new ObjectParameter("trangthai", trangthai) :
                new ObjectParameter("trangthai", typeof(int));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_hoadonUser_Result>("get_hoadonUser", trangthaiParameter, idParameter);
        }
    
        public virtual ObjectResult<get_user_Result> get_user(string taikhoan, string matkhau)
        {
            var taikhoanParameter = taikhoan != null ?
                new ObjectParameter("taikhoan", taikhoan) :
                new ObjectParameter("taikhoan", typeof(string));
    
            var matkhauParameter = matkhau != null ?
                new ObjectParameter("matkhau", matkhau) :
                new ObjectParameter("matkhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_user_Result>("get_user", taikhoanParameter, matkhauParameter);
        }
    
        public virtual ObjectResult<gethoadon_Result> gethoadon(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<gethoadon_Result>("gethoadon", idParameter);
        }
    
        public virtual ObjectResult<getSP_giaMinMax_Result> getSP_giaMinMax(Nullable<int> giaMin, Nullable<int> giaMax)
        {
            var giaMinParameter = giaMin.HasValue ?
                new ObjectParameter("GiaMin", giaMin) :
                new ObjectParameter("GiaMin", typeof(int));
    
            var giaMaxParameter = giaMax.HasValue ?
                new ObjectParameter("GiaMax", giaMax) :
                new ObjectParameter("GiaMax", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getSP_giaMinMax_Result>("getSP_giaMinMax", giaMinParameter, giaMaxParameter);
        }
    
        public virtual ObjectResult<getspbanchay_Result> getspbanchay()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getspbanchay_Result>("getspbanchay");
        }
    
        public virtual ObjectResult<SP_GETMA_Result> SP_GETMA(string ma)
        {
            var maParameter = ma != null ?
                new ObjectParameter("ma", ma) :
                new ObjectParameter("ma", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GETMA_Result>("SP_GETMA", maParameter);
        }
    
        public virtual ObjectResult<SP_GETMALoai_Result> SP_GETMALoai(string maloai)
        {
            var maloaiParameter = maloai != null ?
                new ObjectParameter("maloai", maloai) :
                new ObjectParameter("maloai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GETMALoai_Result>("SP_GETMALoai", maloaiParameter);
        }
    
        public virtual ObjectResult<SP_GETNew_Result> SP_GETNew(string idsanpham)
        {
            var idsanphamParameter = idsanpham != null ?
                new ObjectParameter("idsanpham", idsanpham) :
                new ObjectParameter("idsanpham", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GETNew_Result>("SP_GETNew", idsanphamParameter);
        }
    
        public virtual ObjectResult<SP_GETTEN_Result> SP_GETTEN(string tensp)
        {
            var tenspParameter = tensp != null ?
                new ObjectParameter("tensp", tensp) :
                new ObjectParameter("tensp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GETTEN_Result>("SP_GETTEN", tenspParameter);
        }
    
        public virtual int SP_Themnew(string tensp, Nullable<int> gia, string hinhanhsp, Nullable<int> soluong, string mota, Nullable<int> idsanpham)
        {
            var tenspParameter = tensp != null ?
                new ObjectParameter("tensp", tensp) :
                new ObjectParameter("tensp", typeof(string));
    
            var giaParameter = gia.HasValue ?
                new ObjectParameter("gia", gia) :
                new ObjectParameter("gia", typeof(int));
    
            var hinhanhspParameter = hinhanhsp != null ?
                new ObjectParameter("hinhanhsp", hinhanhsp) :
                new ObjectParameter("hinhanhsp", typeof(string));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            var motaParameter = mota != null ?
                new ObjectParameter("mota", mota) :
                new ObjectParameter("mota", typeof(string));
    
            var idsanphamParameter = idsanpham.HasValue ?
                new ObjectParameter("idsanpham", idsanpham) :
                new ObjectParameter("idsanpham", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Themnew", tenspParameter, giaParameter, hinhanhspParameter, soluongParameter, motaParameter, idsanphamParameter);
        }
    
        public virtual int SP_update(Nullable<int> id, string tensp, Nullable<int> gia, string hinhanhsp, Nullable<int> soluong, string mota, Nullable<int> idsanpham)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var tenspParameter = tensp != null ?
                new ObjectParameter("tensp", tensp) :
                new ObjectParameter("tensp", typeof(string));
    
            var giaParameter = gia.HasValue ?
                new ObjectParameter("gia", gia) :
                new ObjectParameter("gia", typeof(int));
    
            var hinhanhspParameter = hinhanhsp != null ?
                new ObjectParameter("hinhanhsp", hinhanhsp) :
                new ObjectParameter("hinhanhsp", typeof(string));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            var motaParameter = mota != null ?
                new ObjectParameter("mota", mota) :
                new ObjectParameter("mota", typeof(string));
    
            var idsanphamParameter = idsanpham.HasValue ?
                new ObjectParameter("idsanpham", idsanpham) :
                new ObjectParameter("idsanpham", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_update", idParameter, tenspParameter, giaParameter, hinhanhspParameter, soluongParameter, motaParameter, idsanphamParameter);
        }
    
        public virtual ObjectResult<thongkenam_Result> thongkenam(string year)
        {
            var yearParameter = year != null ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<thongkenam_Result>("thongkenam", yearParameter);
        }
    
        public virtual ObjectResult<thongkethang_Result> thongkethang(string year)
        {
            var yearParameter = year != null ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<thongkethang_Result>("thongkethang", yearParameter);
        }
    }
}
